/* Regenerates data/assets.json — the intrinsic pixel size of every file in /assets/images.
 *
 *   node ui/card/assets.build.js [--check]
 *
 * WHY this is a build artifact and not a lookup: render.js runs in Node AND in the
 * browser, so it can never stat a file itself. The sizes have to arrive as data, the
 * same way options.images.cdnBase does. srcset.js then drops every ladder rung the
 * source cannot fill, because Cloudflare's fit=cover UPSCALES rather than declining —
 * a 509px original asked for width=1200 returns 1200x900 and 4x the bytes.
 * Docs: docs/media.md § srcset
 *
 * --check exits nonzero if the manifest is stale, for CI. Dimensions are read from the
 * file headers (PNG IHDR, JPEG SOF) so the script stays dependency-free.
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

const ROOT = new URL('../../', import.meta.url).pathname;
const IMAGES = 'assets/images';
const OUT = new URL('./data/assets.json', import.meta.url).pathname;
/* ES-module mirror so render.js can import the map without JSON import attributes —
   same two-file shape tokens.build.js uses for the token manifest */
const OUT_JS = new URL('./data/assets.data.js', import.meta.url).pathname;

/** PNG: IHDR is always the first chunk, width/height are big-endian u32 at byte 16. */
const pngSize = (buf) =>
	buf.length > 24 && buf.readUInt32BE(0) === 0x89504e47 ? [buf.readUInt32BE(16), buf.readUInt32BE(20)] : null;

/** JPEG: walk the segment chain to a Start Of Frame marker and read its dimensions. */
const jpegSize = (buf) => {
	if (buf.length < 4 || buf.readUInt16BE(0) !== 0xffd8) return null;
	let i = 2;
	while (i < buf.length - 9) {
		if (buf[i] !== 0xff) { i++; continue; } /* resync: padding bytes are legal here */
		const marker = buf[i + 1];
		/* SOF0-SOF15 carry the frame header; C4/C8/CC are Huffman/arithmetic tables, not frames */
		if (marker >= 0xc0 && marker <= 0xcf && ![0xc4, 0xc8, 0xcc].includes(marker))
			return [buf.readUInt16BE(i + 7), buf.readUInt16BE(i + 5)];
		if (marker === 0xd8 || (marker >= 0xd0 && marker <= 0xd9)) { i += 2; continue; }
		i += 2 + buf.readUInt16BE(i + 2);
	}
	return null;
};

export const imageSize = (file) => {
	const buf = readFileSync(file);
	return /\.png$/i.test(file) ? pngSize(buf) : /\.jpe?g$/i.test(file) ? jpegSize(buf) : null;
};

export const buildAssets = () => {
	const dir = join(ROOT, IMAGES);
	const sizes = {};
	const skipped = [];
	for (const name of readdirSync(dir).sort()) {
		const file = join(dir, name);
		if (!statSync(file).isFile() || name.startsWith('.')) continue;
		const size = imageSize(file);
		if (size) sizes[`/${IMAGES}/${name}`] = size;
		else skipped.push(name); /* svg has no raster size; anything else is an unread header */
	}
	return { sizes, skipped };
};

/** Serialise the manifest to its two on-disk forms. */
export const serialise = (sizes) => ({
	json: JSON.stringify({
		note: 'GENERATED by ui/card/assets.build.js — intrinsic [width, height] per asset. Do not hand-edit.',
		sizes
	}, null, 2) + '\n',
	mirror: `/* GENERATED from data/assets.json by assets.build.js — do not edit.
 * Intrinsic [width, height] per asset, so srcset.js can drop ladder rungs the original
 * cannot fill. Docs: docs/media.md § srcset */
export default ${JSON.stringify(sizes, null, '\t')};
`
});

/* CLI only — importing this module must never write to disk (build.js imports it) */
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
	const { sizes, skipped } = buildAssets();
	const { json, mirror } = serialise(sizes);
	if (process.argv.includes('--check')) {
		if (readFileSync(OUT, 'utf8') !== json || readFileSync(OUT_JS, 'utf8') !== mirror) {
			console.error('assets manifest is stale — run: node ui/card/assets.build.js');
			process.exit(1);
		}
		console.log(`assets manifest: ok (${Object.keys(sizes).length} images)`);
	} else {
		writeFileSync(OUT, json);
		writeFileSync(OUT_JS, mirror);
		console.log(`data/assets.json + data/assets.data.js ← ${Object.keys(sizes).length} images${skipped.length ? ` (${skipped.length} without a raster header: ${skipped.join(', ')})` : ''}`);
	}
}
