#!/usr/bin/env python3
"""Generate icon-font.css from icons.json.

    cd ui/icon && npm run build:icons        (python3 -m pip install fonttools brotli)

Regeneration-only: icon-font.css is committed, so consumers never run this.
Docs: readme.md § Icon font.
"""
import base64, json, pathlib, sys, urllib.request

HERE = pathlib.Path(__file__).parent
CACHE = HERE / '.cache'
CFG = json.loads((HERE / 'icons.json').read_text())
OUT_CSS = HERE / 'icon-font.css'
OUT_JS = HERE / 'icons.data.js'
FAMILY = 'ui-icons'


def fetch(url, name):
    CACHE.mkdir(exist_ok=True)
    dest = CACHE / name
    if dest.exists():
        print(f'  cached  {name} ({dest.stat().st_size:,} B)')
        return dest
    print(f'  fetch   {name} …')
    req = urllib.request.Request(url, headers={'User-Agent': 'browser.style-icons-build'})
    with urllib.request.urlopen(req, timeout=180) as r:
        dest.write_bytes(r.read())
    print(f'          {dest.stat().st_size:,} B')
    return dest


def main():
    from fontTools.ttLib import TTFont
    from fontTools.varLib import instancer
    from fontTools import subset

    src = CFG['source']
    print('Sources')
    font_path = fetch(src['font'], 'MaterialSymbolsOutlined.ttf')
    cp_path = fetch(src['codepoints'], 'MaterialSymbolsOutlined.codepoints')

    # name -> codepoint
    table = {}
    for line in cp_path.read_text().splitlines():
        if not line.strip():
            continue
        name, hexcp = line.split()
        table[name] = int(hexcp, 16)

    names = CFG['icons']
    missing = [n for n in names if n not in table]
    if missing:
        sys.exit(f'ERROR: unknown icon name(s): {", ".join(missing)}')
    wanted = {n: table[n] for n in names}

    print('\nBuild')
    font = TTFont(font_path)
    upem = font['head'].unitsPerEm

    axes = src['axes']
    font = instancer.instantiateVariableFont(font, axes, inplace=True, updateFontNames=False)
    print(f'  instanced at {axes}')

    opts = subset.Options()
    opts.layout_features = []
    opts.name_IDs = [1, 2]
    opts.notdef_outline = False
    opts.recalc_bounds = True
    opts.drop_tables += ['GSUB', 'GPOS', 'GDEF', 'STAT', 'gasp', 'DSIG']
    sub = subset.Subsetter(options=opts)
    sub.populate(unicodes=list(wanted.values()))
    sub.subset(font)
    print(f'  subset to {len(wanted)} codepoints')

    # ── The vertical correction. Material Symbols centre their icon box at +0.5em
    #    above the baseline; text centres near +0.33em. ::marker accepts no
    #    vertical-align/transform (measured), so the offset is baked into the glyphs
    #    — which also makes the font correct in ::before with no vertical-align.
    dy = -round(CFG['baselineShiftEm'] * upem)
    glyf = font['glyf']
    shifted = 0
    for name in font.getGlyphOrder():
        g = glyf[name]
        if g.numberOfContours == 0:
            continue
        if g.isComposite():
            for c in g.components:
                c.y += dy
        else:
            g.coordinates.translate((0, dy))
        g.recalcBounds(glyf)
        shifted += 1
    print(f'  baseline shift {CFG["baselineShiftEm"]}em = {dy} units on {shifted} glyphs')

    # fontTools rewrites head.modified to "now" on save() while recalcTimestamp is on (its
    # default), which lands inside the compressed stream and makes every rebuild a
    # byte-different committed artifact. Pin the stamp AND turn the recalc off — either
    # alone is not enough. Docs: readme.md § Icon font
    font.recalcTimestamp = False
    font['head'].modified = font['head'].created = 3155673600

    font.flavor = 'woff2'
    woff2 = HERE / '.cache' / 'subset.woff2'
    font.save(woff2)
    raw = woff2.read_bytes()
    b64 = base64.b64encode(raw).decode()
    print(f'  woff2 {len(raw):,} B  ({len(raw)/len(names):.0f} B/icon)  base64 {len(b64):,} B')

    # ── CSS
    cat = '\n'.join(f'\t\t--icon-{n.replace("_", "-")}: "\\{cp:x}";' for n, cp in wanted.items())
    # the data-icon attribute uses the kebab-case spelling, matching the custom
    # property and the repo's naming rule — the underscore is Material's key only
    maps = '\n'.join(
        f'\t:where([data-icon="{n.replace("_", "-")}"]) {{ --icon: var(--icon-{n.replace("_", "-")}); }}'
        for n in wanted
    )
    css = f"""/* GENERATED by icons.build.py — do not edit. Source: icons.json
   Material Symbols Outlined ({src['license']}), {len(names)} icons, baseline-shifted {CFG['baselineShiftEm']}em.
   Docs: readme.md § Icon font */
@font-face {{
\tfont-display: block;
\tfont-family: '{FAMILY}';
\tfont-style: normal;
\tfont-weight: {axes['wght']};
\tsrc: url(data:font/woff2;base64,{b64}) format('woff2');
}}
@layer bs-component {{
\t:root {{
\t\t--ui-icon-font: '{FAMILY}';
{cat}
\t}}
{maps}
}}
"""
    OUT_CSS.write_text(css)
    print(f'\n  -> {OUT_CSS.relative_to(HERE.parent.parent)} ({len(css):,} B)')

    # ── ES-module mirror of the vocabulary, for editors and other JS consumers
    kebab = [n.replace('_', '-') for n in wanted]
    js = ('/* GENERATED from icons.json by icons.build.py — do not edit.\n'
          ' * ES-module mirror of the icon vocabulary in its data-icon (kebab-case) spelling,\n'
          ' * so an editor can import it without JSON import attributes.\n'
          ' * Docs: readme.md § Icon font */\n'
          'export const ICON_NAMES = [\n'
          + ''.join(f"\t'{n}',\n" for n in kebab)
          + '];\n')
    OUT_JS.write_text(js)
    print(f'  -> {OUT_JS.relative_to(HERE.parent.parent)} ({len(js):,} B, {len(kebab)} names)')


if __name__ == '__main__':
    main()
