/**
 * SSR build for the two schema-mode twins of demo/schema.html.
 *
 *   node ui/card/demo/schema.modes.build.js
 *
 *   schema.raw.html     schema=""       markup with no structured data at all
 *   schema.jsonld.html  schema="jsonld" the same clean markup + one page-level @graph
 *
 * Both are derived from demo/schema.html itself: stripSchema() removes the microdata —
 * exactly what renderCard(…, { schema }) does to its own output — and jsonld.js reads the
 * SAME microdata back out as JSON-LD. So all three pages agree by construction: identical
 * sections, identical 2-column layout, identical cards in identical order, and the only
 * difference is where the structured data lives (inline / nowhere / one script in <head>).
 *
 * It deliberately does NOT re-render from data/index.json. That corpus is render.html's
 * ("every content type, one preset each") and differs from this page: it carries the four
 * standalone product-variant pages schema.html has no section for, and picks different
 * presets. Rendering it produced a page that looked nothing like its supposed twin.
 *
 * Docs: docs/card.md § Schema mode
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { setSchemaMode, stripSchema } from '../render.js';
import { jsonLdScript, microdataToJsonLd } from '../jsonld.js';

const here = dirname(fileURLToPath(import.meta.url));
const source = readFileSync(join(here, 'schema.html'), 'utf8');

/* the graph is read from the MICRODATA — one source of structured data, never a second
   mapping. <head> carries no items, so only the body is scanned. */
const graph = microdataToJsonLd(source.slice(source.indexOf('<body')));
const script = jsonLdScript(source.slice(source.indexOf('<body')), '\t');

/* stripSchema() is a no-op in micro mode — arm the mode first */
setSchemaMode('');
const stripped = stripSchema(source);
setSchemaMode('micro');

const build = ({ file, title, blurb, description, head = '' }) => {
	let page = stripped;
	const swap = (from, to) => {
		if (!page.includes(from)) throw new Error(`schema.modes.build: schema.html no longer contains ${JSON.stringify(from.slice(0, 60))}`);
		page = page.replace(from, to);
	};
	swap('<title>UI: Card — Schema.org</title>', `<title>${title}</title>`);
	swap('<h1>UI: Card — Schema.org</h1>', `<h1>${title}</h1>\n\t${blurb}`);
	swap('<span>Schema.org</span>', `<span>${title.replace('UI: Card — ', '')}</span>`);
	page = page.replace(/<meta name="description" content="[^"]*">/, `<meta name="description" content="${description}">`);
	page = page.replace('<link rel="alternate" type="text/markdown" href="/ui/card/docs/schema.md">',
		`<link rel="alternate" type="text/markdown" href="/ui/card/docs/card.md">${head}`);

	writeFileSync(join(here, file), page);
	/* attribute forms only — the prose names the attributes in <code> */
	const leftover = (page.replace(/<script type="application\/ld\+json">[\s\S]*?<\/script>/, '')
		.match(/ itemprop="| itemscope[ >]| itemtype="/g) || []).length;
	const cards = (page.match(/<ui-card\b/g) || []).length;
	console.log(`${file.padEnd(19)} ← schema.html · ${cards} cards · microdata attributes: ${leftover}`);
	if (leftover) { console.error(`FAILED: ${file} still carries inline structured data`); process.exit(1); }
};

build({
	file: 'schema.raw.html',
	title: 'UI: Card — Schema mode: raw',
	description: 'demo/schema.html with the structured data removed — the same cards, sections and layout, rendered with schema="" so there is no itemscope, itemtype or itemprop and none of the hidden meta blocks that carry machine values.',
	blurb: `<p>This is <a href="schema.html">demo/schema.html</a> rendered with <code>schema=&quot;&quot;</code>.
	Same cards, same sections, same layout — every difference between the two pages is structured data.
	See also <a href="schema.jsonld.html">schema.jsonld.html</a>, which puts that data back as JSON-LD.
	Generated by <code>node ui/card/demo/schema.modes.build.js</code>; do not edit by hand.</p>`
});

build({
	file: 'schema.jsonld.html',
	title: 'UI: Card — Schema mode: JSON-LD',
	description: `demo/schema.html rendered with schema="jsonld": the markup carries no microdata, and the same structured data is emitted once as a page-level @graph of ${graph.length} nodes in the document head.`,
	head: `\n\t${script}`,
	blurb: `<p>This is <a href="schema.html">demo/schema.html</a> rendered with <code>schema=&quot;jsonld&quot;</code>.
	The markup is identical to <a href="schema.raw.html">schema.raw.html</a> — no <code>itemscope</code>,
	<code>itemtype</code> or <code>itemprop</code> — and the same structured data is emitted once in
	<code>&lt;head&gt;</code> as a single <code>@graph</code> of ${graph.length} nodes. It is read back out of the
	microdata by <code>jsonld.js</code>, so it cannot disagree with <a href="schema.html">schema.html</a>.
	Generated by <code>node ui/card/demo/schema.modes.build.js</code>; do not edit by hand.</p>`
});
