/**
 * SSR build for demo/schema.raw.html — the no-structured-data twin of schema.html.
 *
 *   node ui/card/demo/schema.raw.build.js
 *
 * Renders the same corpus demo/render.html drives (data/index.json → cards[]) with
 * `schema: ''`, so every card comes out with no itemscope/itemtype/itemprop and no
 * crawler-only <meta>/<link>/hidden wrapper. The page exists to make raw mode
 * inspectable: view source next to schema.html and the only difference is the
 * structured data.
 *
 * Static, not a client-side driver like render.html, because a static file can be
 * grepped — render.test.js § schema modes asserts the shipped file carries zero
 * itemprop, which a runtime-rendered page could not offer.
 *
 * Docs: docs/card.md § Schema mode
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { renderCard, resolveItemtype } from '../render.js';
import { CONTRAST_STYLE, HEAD_COMMON, esc } from './build.shared.js';

const here = dirname(fileURLToPath(import.meta.url));
const data = (file) => JSON.parse(readFileSync(join(here, '../data', file), 'utf8'));

const presets = { ...data('card.presets.json').presets, ...data('card.presets.demo.json').presets };
const manifest = data('index.json');
const cards = Object.fromEntries([...manifest.cards, ...manifest.shared]
	.map((id) => [id, data(`${id}.json`)]));

const images = { cdnBase: 'https://v4.browser.style', sizes: '(min-width: 540px) min(50vw, 512px), 100vw' };

const sections = manifest.cards.map((id) => {
	const ucf = cards[id];
	const html = renderCard(ucf, presets, cards, { schema: '', images, typeChip: true });
	const preset = ucf.fields?.preset?.$ref?.split('/').pop() || 'stack';
	return `	<h2>${esc(ucf.fields?.internalName || id)} — <code>${esc(resolveItemtype(ucf.fields))} · ${esc(preset)}</code></h2>
	<lay-out md="columns(2) items(start)">${html}</lay-out>`;
}).join('\n');

const TITLE = 'UI: Card — Schema mode: raw';
const DESCRIPTION = `The ${manifest.cards.length} cards of demo/render.html rendered with schema="" — no itemscope, itemtype or itemprop, and none of the hidden <meta> blocks that carry machine values in microdata mode. The visible output is identical to the microdata build; only the structured data is gone. Compare with demo/schema.html.`;

const page = `<!DOCTYPE html>
<html lang="en-US" dir="ltr">
<head>
	<title>${esc(TITLE)}</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
	<meta name="text-scale" content="scale">
	<meta name="color-scheme" content="light dark">
	<!-- the Book card prints an ISBN; iOS data detectors read it as a phone number.
	     Docs: docs/schema.md § Book -->
	<meta name="format-detection" content="telephone=no">
	<meta name="description" content="${esc(DESCRIPTION)}">
	<link rel="alternate" type="text/markdown" href="/ui/card/docs/card.md">
	${HEAD_COMMON}
	<style>
		/* Off-screen cards skip style+layout — same block as demo/render.html */
		main > lay-out > ui-card,
		main > lay-out > ui-reveal { content-visibility: auto; contain-intrinsic-size: auto 567px; }
	</style>
	${CONTRAST_STYLE}
</head>
<body data-layout-root data-page-gap="2">
	<h1>${esc(TITLE)}</h1>
	<p>Every card below is rendered with <code>schema=&quot;&quot;</code> — the renderer emits no
	<code>itemscope</code>, <code>itemtype</code> or <code>itemprop</code>, and the hidden
	<code>&lt;meta&gt;</code> blocks that carry machine values in microdata mode are gone with them.
	The visible output is byte-for-byte the same content as the default build; only the structured
	data differs. The microdata version is <a href="schema.html">demo/schema.html</a>.</p>
	<p class="note">Generated by <code>node ui/card/demo/schema.raw.build.js</code> — do not edit by hand.</p>

	<main data-layout-root data-page-gap="2">
${sections}
	</main>
</body>
</html>
`;

const out = join(here, 'schema.raw.html');
writeFileSync(out, page);
/* attribute forms only — the prose above deliberately names the attributes in <code> */
const leftover = (page.match(/ itemprop="| itemscope[ >]| itemtype="/g) || []).length;
console.log(`schema.raw.html ← ${manifest.cards.length} cards · microdata attributes: ${leftover}`);
if (leftover) { console.error('FAILED: raw page still carries structured data'); process.exit(1); }
