/**
 * SSR build for demo/schema.raw.html — schema.html with the structured data removed.
 *
 *   node ui/card/demo/schema.raw.build.js
 *
 * It reads demo/schema.html and runs the renderer's own stripSchema() over it, which is
 * exactly what `renderCard(…, { schema: '' })` does to its output. So the two pages are
 * identical by construction — same sections, same 2-column layout, same cards in the same
 * order — and the ONLY difference is the microdata. That is the point: view source side by
 * side and every remaining difference is structured data.
 *
 * It deliberately does NOT re-render from data/index.json. That corpus is render.html's
 * ("every content type, one preset each") and differs from this page: it carries the four
 * standalone product-variant pages schema.html has no section for, and picks different
 * presets. Rendering it produced a page that looked nothing like its supposed twin.
 *
 * Docs: docs/card.md § Schema mode
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { setSchemaMode, stripSchema } from '../render.js';

const here = dirname(fileURLToPath(import.meta.url));
const source = join(here, 'schema.html');
const out = join(here, 'schema.raw.html');

/* stripSchema() is a no-op in micro mode — arm the mode first */
setSchemaMode('');
let page = stripSchema(readFileSync(source, 'utf8'));
setSchemaMode('micro');

const TITLE = 'UI: Card — Schema mode: raw';
const DESCRIPTION = 'demo/schema.html with the structured data removed — the same 60 cards, the same sections and the same layout, rendered with schema="" so there is no itemscope, itemtype or itemprop and none of the hidden meta blocks that carry machine values. Every difference between this page and schema.html is structured data.';

const swap = (from, to) => {
	if (!page.includes(from)) throw new Error(`schema.raw.build: source no longer contains ${JSON.stringify(from.slice(0, 60))}`);
	page = page.replace(from, to);
};

swap('<title>UI: Card — Schema.org</title>', `<title>${TITLE}</title>`);
swap('<h1>UI: Card — Schema.org</h1>', `<h1>${TITLE}</h1>
	<p>This is <a href="schema.html">demo/schema.html</a> rendered with <code>schema=&quot;&quot;</code>.
	Same cards, same sections, same layout — every difference between the two pages is structured
	data. Generated by <code>node ui/card/demo/schema.raw.build.js</code>; do not edit by hand.</p>`);
swap('<span>Schema.org</span>', '<span>Schema mode: raw</span>');   // breadcrumb leaf — itemprop already stripped
page = page.replace(/<meta name="description" content="[^"]*">/, `<meta name="description" content="${DESCRIPTION}">`);
page = page.replace('<link rel="alternate" type="text/markdown" href="/ui/card/docs/schema.md">',
	'<link rel="alternate" type="text/markdown" href="/ui/card/docs/card.md">');

writeFileSync(out, page);

/* attribute forms only — the prose above names the attributes in <code> */
const leftover = (page.match(/ itemprop="| itemscope[ >]| itemtype="/g) || []).length;
const cards = (page.match(/<ui-card\b/g) || []).length;
const lays = (page.match(/<lay-out\b/g) || []).length;
console.log(`schema.raw.html ← schema.html · ${cards} cards in ${lays} lay-outs · microdata attributes: ${leftover}`);
if (leftover) { console.error('FAILED: raw page still carries structured data'); process.exit(1); }
